# ezl zsh configuration

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(
    git
    docker
    docker-compose
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# shellcheck disable=SC1091
[[ -f "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

# ---- user preferences --------------------------------------------------------
export EDITOR=vim
export VISUAL=vim
export PAGER=less

# local bin
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# ---- tool init (added by ezl modules) ---------------------------------------
# SDKMAN
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# nvm
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
if [[ -d "$PYENV_ROOT" ]]; then
    export PATH="$PYENV_ROOT/bin:$PATH"
    command -v pyenv >/dev/null && eval "$(pyenv init -)"
fi

# .NET
export DOTNET_ROOT="$HOME/.dotnet"
[[ -d "$DOTNET_ROOT" ]] && export PATH="$DOTNET_ROOT:$PATH"

# Go
[[ -d /usr/local/go/bin ]] && export PATH="/usr/local/go/bin:$PATH"

# aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias k='kubectl'
alias d='docker'
alias dc='docker compose'
alias lzd='lazydocker'

# WSL specific helpers
if grep -qi microsoft /proc/version 2>/dev/null; then
    # use Windows chrome as browser if available
    export BROWSER="/mnt/c/Program Files/Google/Chrome/Application/chrome.exe"
fi
